const mongoose = require("mongoose");
const dotenv = require("dotenv");
dotenv.config({ path: "../.env" });
dotenv.config();

const College = require("../models/College");

const MONGO_URI = process.env.MONGO_URI || "mongodb://localhost:27017/college_discovery";

const colleges = [
  {
    name: "Indian Institute of Technology Bombay",
    slug: "iit-bombay",
    location: { city: "Mumbai", state: "Maharashtra" },
    fees: 228000,
    maxFees: 300000,
    rating: 4.8,
    totalRatings: 1200,
    type: "IIT",
    established: 1958,
    nirf_rank: 3,
    accreditation: "A++",
    description:
      "IIT Bombay is one of the premier engineering institutes in India, known for cutting-edge research and top-notch placements. Located in Powai, Mumbai, it offers undergraduate, postgraduate and doctoral programs.",
    website: "https://www.iitb.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/IIT_Bombay_Main_Gate.jpg/640px-IIT_Bombay_Main_Gate.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 228000, seats: 120, type: "UG" },
      { name: "B.Tech Electrical Engineering", duration: "4 years", fees: 228000, seats: 80, type: "UG" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 228000, seats: 70, type: "UG" },
      { name: "M.Tech Computer Science", duration: "2 years", fees: 72000, seats: 60, type: "PG" },
      { name: "MBA (SJMSOM)", duration: "2 years", fees: 900000, seats: 120, type: "PG" },
    ],
    placements: {
      averagePackage: 25,
      highestPackage: 2.5,
      placementRate: 95,
      topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey", "Amazon"],
      year: 2024,
    },
    reviews: [
      { author: "Rahul Sharma", rating: 5, comment: "World-class faculty and infrastructure. Best decision of my life to come here.", batch: "2022", date: new Date("2024-05-10") },
      { author: "Priya Nair", rating: 5, comment: "Incredible research opportunities and industry exposure. Placements are phenomenal.", batch: "2023", date: new Date("2024-06-15") },
      { author: "Arjun Mehta", rating: 4, comment: "Tough curriculum but worth every moment. The peer group is exceptional.", batch: "2021", date: new Date("2024-03-20") },
    ],
    cutoffs: [
      { exam: "JEE Advanced", category: "General", rankMin: 1, rankMax: 500, course: "B.Tech Computer Science" },
      { exam: "JEE Advanced", category: "General", rankMin: 1, rankMax: 800, course: "B.Tech Electrical Engineering" },
      { exam: "JEE Advanced", category: "OBC", rankMin: 1, rankMax: 250, course: "B.Tech Computer Science" },
      { exam: "JEE Advanced", category: "SC", rankMin: 1, rankMax: 150, course: "B.Tech Computer Science" },
      { exam: "GATE", category: "General", rankMin: 1, rankMax: 200, course: "M.Tech Computer Science" },
    ],
  },
  {
    name: "Indian Institute of Technology Delhi",
    slug: "iit-delhi",
    location: { city: "New Delhi", state: "Delhi" },
    fees: 228000,
    maxFees: 290000,
    rating: 4.8,
    totalRatings: 1100,
    type: "IIT",
    established: 1961,
    nirf_rank: 2,
    accreditation: "A++",
    description:
      "IIT Delhi is ranked among the top engineering institutions in Asia. Situated in Hauz Khas, New Delhi, it is renowned for research output and industry connections.",
    website: "https://home.iitd.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/IIT_Delhi_Main_Gate.jpg/640px-IIT_Delhi_Main_Gate.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 228000, seats: 110, type: "UG" },
      { name: "B.Tech Civil Engineering", duration: "4 years", fees: 228000, seats: 60, type: "UG" },
      { name: "B.Tech Chemical Engineering", duration: "4 years", fees: 228000, seats: 55, type: "UG" },
      { name: "M.Tech Electronics", duration: "2 years", fees: 72000, seats: 50, type: "PG" },
    ],
    placements: {
      averagePackage: 26,
      highestPackage: 3.0,
      placementRate: 96,
      topRecruiters: ["Google", "Facebook", "Adobe", "Qualcomm", "Samsung"],
      year: 2024,
    },
    reviews: [
      { author: "Sneha Gupta", rating: 5, comment: "Being in the capital gives amazing networking opportunities. Faculty is top-notch.", batch: "2022", date: new Date("2024-04-12") },
      { author: "Vikram Singh", rating: 4, comment: "Great campus life, strong alumni network. Curriculum can be overwhelming at times.", batch: "2023", date: new Date("2024-07-01") },
    ],
    cutoffs: [
      { exam: "JEE Advanced", category: "General", rankMin: 1, rankMax: 450, course: "B.Tech Computer Science" },
      { exam: "JEE Advanced", category: "General", rankMin: 1, rankMax: 900, course: "B.Tech Civil Engineering" },
      { exam: "JEE Advanced", category: "OBC", rankMin: 1, rankMax: 220, course: "B.Tech Computer Science" },
      { exam: "GATE", category: "General", rankMin: 1, rankMax: 150, course: "M.Tech Electronics" },
    ],
  },
  {
    name: "National Institute of Technology Trichy",
    slug: "nit-trichy",
    location: { city: "Tiruchirappalli", state: "Tamil Nadu" },
    fees: 175000,
    maxFees: 200000,
    rating: 4.5,
    totalRatings: 890,
    type: "NIT",
    established: 1964,
    nirf_rank: 9,
    accreditation: "A+",
    description:
      "NIT Trichy is consistently ranked among the top NITs in India. Known for its vibrant campus culture, strong alumni base and excellent placement record across engineering disciplines.",
    website: "https://www.nitt.edu",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/NIT_Trichy.jpg/640px-NIT_Trichy.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 175000, seats: 90, type: "UG" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 175000, seats: 120, type: "UG" },
      { name: "B.Tech Electronics & Communication", duration: "4 years", fees: 175000, seats: 100, type: "UG" },
      { name: "M.Tech Structural Engineering", duration: "2 years", fees: 50000, seats: 30, type: "PG" },
    ],
    placements: {
      averagePackage: 12,
      highestPackage: 45,
      placementRate: 88,
      topRecruiters: ["TCS", "Infosys", "Wipro", "Cognizant", "L&T"],
      year: 2024,
    },
    reviews: [
      { author: "Karthik R", rating: 5, comment: "Best NIT in India without question. Placement cell is very proactive.", batch: "2022", date: new Date("2024-02-15") },
      { author: "Meena Devi", rating: 4, comment: "Amazing campus, great food, solid academics. Highly recommend.", batch: "2023", date: new Date("2024-08-10") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 1000, rankMax: 5000, course: "B.Tech Computer Science" },
      { exam: "JEE Main", category: "General", rankMin: 5000, rankMax: 15000, course: "B.Tech Mechanical Engineering" },
      { exam: "JEE Main", category: "OBC", rankMin: 500, rankMax: 2500, course: "B.Tech Computer Science" },
      { exam: "JEE Main", category: "SC", rankMin: 200, rankMax: 800, course: "B.Tech Computer Science" },
    ],
  },
  {
    name: "BITS Pilani",
    slug: "bits-pilani",
    location: { city: "Pilani", state: "Rajasthan" },
    fees: 550000,
    maxFees: 600000,
    rating: 4.6,
    totalRatings: 950,
    type: "Deemed",
    established: 1964,
    nirf_rank: 26,
    accreditation: "A+",
    description:
      "BITS Pilani is India's top private engineering university. Its BITSAT entrance exam is highly competitive and the unique dual degree program and practice school internships set it apart.",
    website: "https://www.bits-pilani.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/BITS_Pilani_University.jpg/640px-BITS_Pilani_University.jpg",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 550000, seats: 150, type: "UG" },
      { name: "B.E. Electronics & Instrumentation", duration: "4 years", fees: 550000, seats: 80, type: "UG" },
      { name: "B.Pharma", duration: "4 years", fees: 480000, seats: 60, type: "UG" },
      { name: "M.E. Software Systems", duration: "2 years", fees: 200000, seats: 40, type: "PG" },
    ],
    placements: {
      averagePackage: 18,
      highestPackage: 2.2,
      placementRate: 90,
      topRecruiters: ["Microsoft", "Oracle", "Cisco", "Deutsche Bank", "Goldman Sachs"],
      year: 2024,
    },
    reviews: [
      { author: "Ananya Kapoor", rating: 5, comment: "The freedom to choose your curriculum is unmatched. Practice school is a life-changing experience.", batch: "2022", date: new Date("2024-01-20") },
      { author: "Rohan Joshi", rating: 4, comment: "High fees but worth it for the quality and brand value. Campus is beautiful.", batch: "2023", date: new Date("2024-09-05") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 2000, rankMax: 10000, course: "B.E. Computer Science" },
      { exam: "JEE Main", category: "General", rankMin: 5000, rankMax: 20000, course: "B.E. Electronics & Instrumentation" },
    ],
  },
  {
    name: "Indian Institute of Management Ahmedabad",
    slug: "iim-ahmedabad",
    location: { city: "Ahmedabad", state: "Gujarat" },
    fees: 2400000,
    maxFees: 2400000,
    rating: 4.9,
    totalRatings: 800,
    type: "Government",
    established: 1961,
    nirf_rank: 1,
    accreditation: "A++",
    description:
      "IIM Ahmedabad is the #1 business school in India and among the best in Asia. Its two-year PGP (MBA equivalent) program is highly sought after, with placements at top global companies.",
    website: "https://www.iima.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/IIM_Ahmedabad_-_Old_campus.jpg/640px-IIM_Ahmedabad_-_Old_campus.jpg",
    courses: [
      { name: "PGP (MBA)", duration: "2 years", fees: 2400000, seats: 385, type: "PG" },
      { name: "PGP-FABM", duration: "2 years", fees: 2000000, seats: 60, type: "PG" },
      { name: "Executive MBA", duration: "1 year", fees: 3200000, seats: 100, type: "PG" },
    ],
    placements: {
      averagePackage: 35,
      highestPackage: 7.5,
      placementRate: 100,
      topRecruiters: ["McKinsey", "BCG", "Bain", "Goldman Sachs", "Amazon"],
      year: 2024,
    },
    reviews: [
      { author: "Deepika Rao", rating: 5, comment: "Transformative experience. The case study method and peer learning is unbeatable.", batch: "2022", date: new Date("2024-05-25") },
      { author: "Amit Verma", rating: 5, comment: "If you get in, your life changes. The alumni network is worth millions.", batch: "2023", date: new Date("2024-10-01") },
    ],
    cutoffs: [
      { exam: "CAT", category: "General", rankMin: 1, rankMax: 50, course: "PGP (MBA)" },
      { exam: "CAT", category: "OBC", rankMin: 1, rankMax: 30, course: "PGP (MBA)" },
      { exam: "CAT", category: "SC", rankMin: 1, rankMax: 20, course: "PGP (MBA)" },
    ],
  },
  {
    name: "Vellore Institute of Technology",
    slug: "vit-vellore",
    location: { city: "Vellore", state: "Tamil Nadu" },
    fees: 400000,
    maxFees: 500000,
    rating: 4.1,
    totalRatings: 2100,
    type: "Deemed",
    established: 1984,
    nirf_rank: 11,
    accreditation: "A+",
    description:
      "VIT Vellore is one of India's largest private universities with state-of-the-art infrastructure. Known for its industry-oriented curriculum and strong placement record.",
    website: "https://vit.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/VIT_main_gate.jpg/640px-VIT_main_gate.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 400000, seats: 600, type: "UG" },
      { name: "B.Tech AI & Machine Learning", duration: "4 years", fees: 430000, seats: 200, type: "UG" },
      { name: "B.Tech Biotechnology", duration: "4 years", fees: 380000, seats: 100, type: "UG" },
      { name: "M.Tech Data Science", duration: "2 years", fees: 250000, seats: 60, type: "PG" },
    ],
    placements: {
      averagePackage: 8,
      highestPackage: 50,
      placementRate: 82,
      topRecruiters: ["TCS", "Infosys", "HCL", "Zoho", "Amazon"],
      year: 2024,
    },
    reviews: [
      { author: "Lakshmi N", rating: 4, comment: "Great infrastructure and variety of clubs. Placements depend on your branch.", batch: "2022", date: new Date("2024-03-10") },
      { author: "Rahul P", rating: 4, comment: "Good for networking. VITESSE and other fests are amazing.", batch: "2023", date: new Date("2024-07-20") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 15000, rankMax: 80000, course: "B.Tech Computer Science" },
      { exam: "JEE Main", category: "General", rankMin: 30000, rankMax: 120000, course: "B.Tech Biotechnology" },
    ],
  },
  {
    name: "Delhi Technological University",
    slug: "dtu-delhi",
    location: { city: "New Delhi", state: "Delhi" },
    fees: 170000,
    maxFees: 200000,
    rating: 4.2,
    totalRatings: 750,
    type: "Government",
    established: 1941,
    nirf_rank: 36,
    accreditation: "A",
    description:
      "Delhi Technological University (formerly DCE) is Delhi's premier state technical university. Strategically located in the capital, it offers excellent placement opportunities.",
    website: "https://dtu.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Delhi_Technological_University_Campus.jpg/640px-Delhi_Technological_University_Campus.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 170000, seats: 180, type: "UG" },
      { name: "B.Tech Software Engineering", duration: "4 years", fees: 170000, seats: 90, type: "UG" },
      { name: "B.Tech Electronics & Communication", duration: "4 years", fees: 170000, seats: 120, type: "UG" },
    ],
    placements: {
      averagePackage: 14,
      highestPackage: 80,
      placementRate: 85,
      topRecruiters: ["Microsoft", "Amazon", "Samsung", "Deloitte", "Paytm"],
      year: 2024,
    },
    reviews: [
      { author: "Aditya Kumar", rating: 4, comment: "Best govt college in Delhi outside IIT. Location is a huge advantage.", batch: "2022", date: new Date("2024-04-05") },
      { author: "Sakshi M", rating: 4, comment: "Good faculty and amazing placement cell. Campus is clean and safe.", batch: "2023", date: new Date("2024-06-30") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 8000, rankMax: 25000, course: "B.Tech Computer Science" },
      { exam: "JEE Main", category: "OBC", rankMin: 4000, rankMax: 12000, course: "B.Tech Computer Science" },
      { exam: "JEE Main", category: "General", rankMin: 20000, rankMax: 60000, course: "B.Tech Electronics & Communication" },
    ],
  },
  {
    name: "IIIT Hyderabad",
    slug: "iiit-hyderabad",
    location: { city: "Hyderabad", state: "Telangana" },
    fees: 380000,
    maxFees: 400000,
    rating: 4.5,
    totalRatings: 620,
    type: "IIIT",
    established: 1998,
    nirf_rank: 33,
    accreditation: "A",
    description:
      "IIIT Hyderabad is a research university par excellence. Known for its strong focus on AI, NLP and computer science research. Produces world-class researchers and product engineers.",
    website: "https://www.iiit.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/IIIT_Hyderabad_Campus.jpg/640px-IIIT_Hyderabad_Campus.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 380000, seats: 120, type: "UG" },
      { name: "B.Tech Electronics & Communication", duration: "4 years", fees: 380000, seats: 60, type: "UG" },
      { name: "M.Tech Computer Science", duration: "2 years", fees: 200000, seats: 80, type: "PG" },
      { name: "PhD Computer Science", duration: "4-5 years", fees: 60000, seats: 40, type: "PhD" },
    ],
    placements: {
      averagePackage: 22,
      highestPackage: 1.8,
      placementRate: 92,
      topRecruiters: ["Google", "Microsoft", "Amazon", "Uber", "Qualcomm"],
      year: 2024,
    },
    reviews: [
      { author: "Siddharth T", rating: 5, comment: "Best place for research in CS. Faculty are literally world-famous researchers.", batch: "2022", date: new Date("2024-02-28") },
      { author: "Pooja V", rating: 4, comment: "Small campus but intellectually stimulating environment. Very research-driven.", batch: "2023", date: new Date("2024-09-15") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 3000, rankMax: 12000, course: "B.Tech Computer Science" },
      { exam: "JEE Advanced", category: "General", rankMin: 500, rankMax: 2000, course: "B.Tech Computer Science" },
    ],
  },
  {
    name: "Manipal Institute of Technology",
    slug: "manipal-institute-of-technology",
    location: { city: "Manipal", state: "Karnataka" },
    fees: 470000,
    maxFees: 520000,
    rating: 4.0,
    totalRatings: 1800,
    type: "Private",
    established: 1957,
    nirf_rank: 48,
    accreditation: "A+",
    description:
      "MIT Manipal is one of the oldest and most prestigious private engineering colleges. Known for its international student body, strong alumni network and beautiful coastal campus.",
    website: "https://manipal.edu/mit.html",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/MIT_Manipal_Main_Building.jpg/640px-MIT_Manipal_Main_Building.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 470000, seats: 300, type: "UG" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 460000, seats: 150, type: "UG" },
      { name: "B.Tech Aeronautical Engineering", duration: "4 years", fees: 490000, seats: 60, type: "UG" },
      { name: "M.Tech Robotics", duration: "2 years", fees: 200000, seats: 30, type: "PG" },
    ],
    placements: {
      averagePackage: 9,
      highestPackage: 42,
      placementRate: 78,
      topRecruiters: ["Infosys", "TCS", "Wipro", "Bosch", "Volvo"],
      year: 2024,
    },
    reviews: [
      { author: "Ashwin K", rating: 4, comment: "Beautiful campus near the sea. Amazing extracurricular scene and inter-college fests.", batch: "2022", date: new Date("2024-01-10") },
      { author: "Divya M", rating: 4, comment: "Good faculty, diverse student body. Worth the fees for the overall experience.", batch: "2023", date: new Date("2024-08-25") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 30000, rankMax: 100000, course: "B.Tech Computer Science" },
      { exam: "JEE Main", category: "General", rankMin: 50000, rankMax: 150000, course: "B.Tech Mechanical Engineering" },
    ],
  },
  {
    name: "NIT Warangal",
    slug: "nit-warangal",
    location: { city: "Warangal", state: "Telangana" },
    fees: 160000,
    maxFees: 185000,
    rating: 4.4,
    totalRatings: 700,
    type: "NIT",
    established: 1959,
    nirf_rank: 18,
    accreditation: "A",
    description:
      "NIT Warangal is the first NIT to be established in India. It has produced some of the country's finest engineers and scientists over six decades.",
    website: "https://www.nitw.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/NIT_Warangal_Main_Building.jpg/640px-NIT_Warangal_Main_Building.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 160000, seats: 90, type: "UG" },
      { name: "B.Tech Civil Engineering", duration: "4 years", fees: 160000, seats: 80, type: "UG" },
      { name: "B.Tech Chemical Engineering", duration: "4 years", fees: 160000, seats: 60, type: "UG" },
      { name: "M.Tech VLSI Design", duration: "2 years", fees: 50000, seats: 30, type: "PG" },
    ],
    placements: {
      averagePackage: 11,
      highestPackage: 60,
      placementRate: 86,
      topRecruiters: ["TCS", "Infosys", "Amazon", "Microsoft", "BHEL"],
      year: 2024,
    },
    reviews: [
      { author: "Ravi T", rating: 4, comment: "First NIT of India. Legacy and pride are unmatched. Great faculty.", batch: "2022", date: new Date("2024-03-30") },
      { author: "Sunita R", rating: 5, comment: "Affordable and prestigious. Campus culture is amazing.", batch: "2023", date: new Date("2024-05-15") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 3000, rankMax: 10000, course: "B.Tech Computer Science" },
      { exam: "JEE Main", category: "General", rankMin: 10000, rankMax: 30000, course: "B.Tech Civil Engineering" },
      { exam: "JEE Main", category: "OBC", rankMin: 1500, rankMax: 5000, course: "B.Tech Computer Science" },
    ],
  },
  {
    name: "Jadavpur University",
    slug: "jadavpur-university",
    location: { city: "Kolkata", state: "West Bengal" },
    fees: 15000,
    maxFees: 20000,
    rating: 4.3,
    totalRatings: 650,
    type: "Government",
    established: 1906,
    nirf_rank: 12,
    accreditation: "A++",
    description:
      "Jadavpur University is one of India's top research-intensive universities. Famous for its incredibly low fees and quality education, it is particularly strong in engineering and humanities.",
    website: "https://jadavpuruniversity.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Jadavpur_University_Main_Gate.jpg/640px-Jadavpur_University_Main_Gate.jpg",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 15000, seats: 60, type: "UG" },
      { name: "B.E. Electrical Engineering", duration: "4 years", fees: 15000, seats: 80, type: "UG" },
      { name: "B.E. Mechanical Engineering", duration: "4 years", fees: 15000, seats: 100, type: "UG" },
      { name: "M.E. Computer Science", duration: "2 years", fees: 8000, seats: 40, type: "PG" },
    ],
    placements: {
      averagePackage: 10,
      highestPackage: 40,
      placementRate: 80,
      topRecruiters: ["TCS", "Cognizant", "IBM", "TATA Steel", "Wipro"],
      year: 2024,
    },
    reviews: [
      { author: "Sourav B", rating: 5, comment: "Incredible value for money. World-class education at government fees. Proud to be a JU alum.", batch: "2022", date: new Date("2024-02-05") },
      { author: "Pritha D", rating: 4, comment: "Strong academic culture. Lots of independent research opportunities.", batch: "2023", date: new Date("2024-07-12") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 8000, rankMax: 30000, course: "B.E. Computer Science" },
      { exam: "State CET", category: "General", rankMin: 1, rankMax: 500, course: "B.E. Computer Science" },
    ],
  },
  {
    name: "IIT Madras",
    slug: "iit-madras",
    location: { city: "Chennai", state: "Tamil Nadu" },
    fees: 228000,
    maxFees: 280000,
    rating: 4.9,
    totalRatings: 1050,
    type: "IIT",
    established: 1959,
    nirf_rank: 1,
    accreditation: "A++",
    description:
      "IIT Madras has been ranked #1 in India by NIRF for 9 consecutive years. Located inside a protected forest reserve, it offers a unique campus experience alongside world-class academics.",
    website: "https://www.iitm.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/IIT-Madras-2007.jpg/640px-IIT-Madras-2007.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 228000, seats: 100, type: "UG" },
      { name: "B.Tech Aerospace Engineering", duration: "4 years", fees: 228000, seats: 50, type: "UG" },
      { name: "B.Tech Ocean Engineering", duration: "4 years", fees: 228000, seats: 40, type: "UG" },
      { name: "M.Tech AI", duration: "2 years", fees: 72000, seats: 60, type: "PG" },
    ],
    placements: {
      averagePackage: 27,
      highestPackage: 4.0,
      placementRate: 94,
      topRecruiters: ["Google", "Apple", "NVIDIA", "Qualcomm", "McKinsey"],
      year: 2024,
    },
    reviews: [
      { author: "Varun K", rating: 5, comment: "Living inside a forest while studying at India's best university is surreal. Pure joy.", batch: "2022", date: new Date("2024-06-01") },
      { author: "Nandini S", rating: 5, comment: "World-class research and startup ecosystem (IITM Pravartak is famous).", batch: "2023", date: new Date("2024-11-10") },
    ],
    cutoffs: [
      { exam: "JEE Advanced", category: "General", rankMin: 1, rankMax: 400, course: "B.Tech Computer Science" },
      { exam: "JEE Advanced", category: "General", rankMin: 400, rankMax: 1200, course: "B.Tech Aerospace Engineering" },
      { exam: "JEE Advanced", category: "OBC", rankMin: 1, rankMax: 200, course: "B.Tech Computer Science" },
    ],
  },
  {
    name: "SRM Institute of Science and Technology",
    slug: "srm-institute",
    location: { city: "Kattankulathur", state: "Tamil Nadu" },
    fees: 400000,
    maxFees: 450000,
    rating: 3.9,
    totalRatings: 2500,
    type: "Private",
    established: 1985,
    nirf_rank: 41,
    accreditation: "A+",
    description:
      "SRM is one of India's largest private universities with a student population of 50,000+. Known for its modern infrastructure, research centres and wide range of engineering programs.",
    website: "https://www.srmist.edu.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/SRM_University_Main_Building.jpg/640px-SRM_University_Main_Building.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 400000, seats: 1000, type: "UG" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 380000, seats: 400, type: "UG" },
      { name: "B.Tech Biomedical Engineering", duration: "4 years", fees: 360000, seats: 100, type: "UG" },
    ],
    placements: {
      averagePackage: 7,
      highestPackage: 40,
      placementRate: 75,
      topRecruiters: ["TCS", "Infosys", "Wipro", "HCL", "Accenture"],
      year: 2024,
    },
    reviews: [
      { author: "Sanjay N", rating: 4, comment: "Great infrastructure and active student life. Placements are decent for core IT.", batch: "2022", date: new Date("2024-04-22") },
      { author: "Anjali G", rating: 3, comment: "Large campus can feel impersonal. Focus on which specialisation you pick.", batch: "2023", date: new Date("2024-08-05") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 50000, rankMax: 200000, course: "B.Tech Computer Science" },
    ],
  },
  {
    name: "Anna University",
    slug: "anna-university",
    location: { city: "Chennai", state: "Tamil Nadu" },
    fees: 120000,
    maxFees: 150000,
    rating: 4.1,
    totalRatings: 1100,
    type: "Government",
    established: 1978,
    nirf_rank: 16,
    accreditation: "A+",
    description:
      "Anna University is Tamil Nadu's premier technical university, affiliating over 500 engineering colleges. Its main CEG campus in Chennai is one of the oldest engineering schools in Asia.",
    website: "https://www.annauniv.edu",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Anna_University_Main_Gate.jpg/640px-Anna_University_Main_Gate.jpg",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 120000, seats: 120, type: "UG" },
      { name: "B.E. Electronics & Communication", duration: "4 years", fees: 120000, seats: 120, type: "UG" },
      { name: "M.E. Applied Electronics", duration: "2 years", fees: 45000, seats: 30, type: "PG" },
    ],
    placements: {
      averagePackage: 8,
      highestPackage: 35,
      placementRate: 80,
      topRecruiters: ["TCS", "CTS", "HCL", "Zoho", "Freshworks"],
      year: 2024,
    },
    reviews: [
      { author: "Kirthana L", rating: 4, comment: "Heritage campus with strong academic tradition. Great for core engineering.", batch: "2022", date: new Date("2024-03-15") },
      { author: "Suresh P", rating: 4, comment: "Affordable fees, quality education. The CEG campus has an old-world charm.", batch: "2023", date: new Date("2024-09-20") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 20000, rankMax: 70000, course: "B.E. Computer Science" },
      { exam: "State CET", category: "General", rankMin: 500, rankMax: 3000, course: "B.E. Computer Science" },
    ],
  },
  {
    name: "Amity University Noida",
    slug: "amity-university-noida",
    location: { city: "Noida", state: "Uttar Pradesh" },
    fees: 500000,
    maxFees: 580000,
    rating: 3.7,
    totalRatings: 3000,
    type: "Private",
    established: 2005,
    nirf_rank: 52,
    accreditation: "A+",
    description:
      "Amity University Noida is India's largest private university by enrollment. Known for its business-friendly approach, strong corporate connections and state-of-the-art facilities.",
    website: "https://www.amity.edu",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Amity_University_Noida_entrance.jpg/640px-Amity_University_Noida_entrance.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 500000, seats: 600, type: "UG" },
      { name: "BBA", duration: "3 years", fees: 350000, seats: 500, type: "UG" },
      { name: "MBA", duration: "2 years", fees: 700000, seats: 300, type: "PG" },
      { name: "B.Tech AI & Data Science", duration: "4 years", fees: 520000, seats: 200, type: "UG" },
    ],
    placements: {
      averagePackage: 6.5,
      highestPackage: 35,
      placementRate: 72,
      topRecruiters: ["Infosys", "TCS", "Wipro", "Capgemini", "Deloitte"],
      year: 2024,
    },
    reviews: [
      { author: "Neha T", rating: 4, comment: "Beautiful campus and good management faculty. Industry exposure through guest lectures is excellent.", batch: "2022", date: new Date("2024-02-20") },
      { author: "Mohit S", rating: 3, comment: "Expensive for what you get. But the corporate connections do help in placements.", batch: "2023", date: new Date("2024-06-08") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 80000, rankMax: 300000, course: "B.Tech Computer Science" },
    ],
  },
  {
    name: "IIT Kharagpur",
    slug: "iit-kharagpur",
    location: { city: "Kharagpur", state: "West Bengal" },
    fees: 228000,
    maxFees: 270000,
    rating: 4.7,
    totalRatings: 980,
    type: "IIT",
    established: 1951,
    nirf_rank: 5,
    accreditation: "A++",
    description:
      "IIT Kharagpur is the oldest IIT in India. Spread over 2100 acres, it is the largest IIT by area. Famous for its vibrant campus life, strong alumni network and wide range of disciplines.",
    website: "https://www.iitkgp.ac.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/IIT_Kharagpur_main_gate.jpg/640px-IIT_Kharagpur_main_gate.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 228000, seats: 90, type: "UG" },
      { name: "B.Tech Mining Engineering", duration: "4 years", fees: 228000, seats: 50, type: "UG" },
      { name: "5-Year Dual Degree", duration: "5 years", fees: 228000, seats: 60, type: "UG" },
      { name: "M.Tech Industrial Engineering", duration: "2 years", fees: 72000, seats: 40, type: "PG" },
    ],
    placements: {
      averagePackage: 21,
      highestPackage: 2.0,
      placementRate: 93,
      topRecruiters: ["Google", "Microsoft", "Flipkart", "Goldman Sachs", "BCG"],
      year: 2024,
    },
    reviews: [
      { author: "Debashis M", rating: 5, comment: "Oldest IIT with the most diverse set of programs. Campus life is unparalleled.", batch: "2022", date: new Date("2024-01-30") },
      { author: "Swati J", rating: 4, comment: "The campus is a small city. You never feel bored here. Great alumni network.", batch: "2023", date: new Date("2024-10-20") },
    ],
    cutoffs: [
      { exam: "JEE Advanced", category: "General", rankMin: 1, rankMax: 600, course: "B.Tech Computer Science" },
      { exam: "JEE Advanced", category: "General", rankMin: 600, rankMax: 2000, course: "5-Year Dual Degree" },
      { exam: "JEE Advanced", category: "OBC", rankMin: 1, rankMax: 300, course: "B.Tech Computer Science" },
    ],
  },
  {
    name: "Pune Institute of Computer Technology",
    slug: "pict-pune",
    location: { city: "Pune", state: "Maharashtra" },
    fees: 130000,
    maxFees: 160000,
    rating: 4.2,
    totalRatings: 560,
    type: "Private",
    established: 1983,
    nirf_rank: 75,
    accreditation: "A",
    description:
      "PICT Pune is one of Maharashtra's most reputed private engineering colleges, particularly known for Computer and IT engineering. Strong industry ties with Pune's booming tech ecosystem.",
    website: "https://pict.edu",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/PICT_Pune_Main_Building.jpg/640px-PICT_Pune_Main_Building.jpg",
    courses: [
      { name: "B.E. Computer Engineering", duration: "4 years", fees: 130000, seats: 240, type: "UG" },
      { name: "B.E. Information Technology", duration: "4 years", fees: 130000, seats: 120, type: "UG" },
      { name: "M.E. Computer Engineering", duration: "2 years", fees: 60000, seats: 24, type: "PG" },
    ],
    placements: {
      averagePackage: 8.5,
      highestPackage: 45,
      placementRate: 87,
      topRecruiters: ["Infosys", "Persistent", "KPIT", "Cummins", "Cognizant"],
      year: 2024,
    },
    reviews: [
      { author: "Omkar P", rating: 4, comment: "Best CS college in Pune besides COEPs. Good placements and active coding culture.", batch: "2022", date: new Date("2024-05-05") },
      { author: "Shruti K", rating: 4, comment: "Strong alumni network in Pune IT industry. Faculty is engaged and supportive.", batch: "2023", date: new Date("2024-08-18") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 60000, rankMax: 150000, course: "B.E. Computer Engineering" },
      { exam: "State CET", category: "General", rankMin: 2000, rankMax: 8000, course: "B.E. Computer Engineering" },
    ],
  },
  {
    name: "College of Engineering Pune",
    slug: "coep-pune",
    location: { city: "Pune", state: "Maharashtra" },
    fees: 80000,
    maxFees: 100000,
    rating: 4.3,
    totalRatings: 690,
    type: "Government",
    established: 1854,
    nirf_rank: 43,
    accreditation: "A+",
    description:
      "COEP (now COEP Technological University) is one of Asia's oldest engineering colleges, established in 1854. It is a government autonomous institution known for its century-old traditions and engineering excellence.",
    website: "https://www.coep.org.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/COEP_main_building.jpg/640px-COEP_main_building.jpg",
    courses: [
      { name: "B.Tech Computer Engineering", duration: "4 years", fees: 80000, seats: 120, type: "UG" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 80000, seats: 120, type: "UG" },
      { name: "B.Tech Civil Engineering", duration: "4 years", fees: 80000, seats: 80, type: "UG" },
    ],
    placements: {
      averagePackage: 9,
      highestPackage: 50,
      placementRate: 84,
      topRecruiters: ["Infosys", "TCS", "TATA Motors", "Persistent", "Cummins"],
      year: 2024,
    },
    reviews: [
      { author: "Gaurav B", rating: 5, comment: "Studying in a college older than most countries. The history is incredible. Great education too.", batch: "2022", date: new Date("2024-04-18") },
      { author: "Priyanka W", rating: 4, comment: "Best govt engineering in Pune. Robotics Boat Club is legendary. Affordable fees.", batch: "2023", date: new Date("2024-07-30") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 30000, rankMax: 80000, course: "B.Tech Computer Engineering" },
      { exam: "State CET", category: "General", rankMin: 500, rankMax: 2500, course: "B.Tech Computer Engineering" },
    ],
  },
  {
    name: "Thapar Institute of Engineering and Technology",
    slug: "thapar-institute",
    location: { city: "Patiala", state: "Punjab" },
    fees: 380000,
    maxFees: 420000,
    rating: 4.0,
    totalRatings: 720,
    type: "Deemed",
    established: 1956,
    nirf_rank: 28,
    accreditation: "A",
    description:
      "Thapar Institute is a top deemed university in North India, known for its focus on industry-relevant education, strong engineering programs and excellent placement record for Tier-2 city college.",
    website: "https://www.thapar.edu",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Thapar_University_Main_Building.jpg/640px-Thapar_University_Main_Building.jpg",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 380000, seats: 180, type: "UG" },
      { name: "B.E. Electronics & Communication", duration: "4 years", fees: 380000, seats: 120, type: "UG" },
      { name: "B.E. Chemical Engineering", duration: "4 years", fees: 360000, seats: 80, type: "UG" },
    ],
    placements: {
      averagePackage: 10,
      highestPackage: 55,
      placementRate: 83,
      topRecruiters: ["Amazon", "Samsung", "Infosys", "Wipro", "Bain & Co"],
      year: 2024,
    },
    reviews: [
      { author: "Harpreet S", rating: 4, comment: "Best engineering college in Punjab by far. Good placements for the location.", batch: "2022", date: new Date("2024-03-08") },
      { author: "Komal B", rating: 4, comment: "Thapar grads are well-respected across India. Active tech culture on campus.", batch: "2023", date: new Date("2024-06-22") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 20000, rankMax: 70000, course: "B.E. Computer Science" },
      { exam: "JEE Main", category: "OBC", rankMin: 10000, rankMax: 35000, course: "B.E. Computer Science" },
    ],
  },
  {
    name: "Symbiosis Institute of Technology",
    slug: "sit-pune",
    location: { city: "Pune", state: "Maharashtra" },
    fees: 350000,
    maxFees: 400000,
    rating: 3.8,
    totalRatings: 480,
    type: "Private",
    established: 2008,
    nirf_rank: 84,
    accreditation: "A",
    description:
      "SIT Pune is a reputed private engineering college under Symbiosis International University. Known for its focus on industry collaboration, international exposure and entrepreneurship.",
    website: "https://www.sitpune.edu.in",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/SIT_Symbiosis_Campus.jpg/640px-SIT_Symbiosis_Campus.jpg",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 350000, seats: 180, type: "UG" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 340000, seats: 60, type: "UG" },
      { name: "M.Tech Computer Science", duration: "2 years", fees: 180000, seats: 30, type: "PG" },
    ],
    placements: {
      averagePackage: 7.5,
      highestPackage: 30,
      placementRate: 78,
      topRecruiters: ["Infosys", "Capgemini", "KPIT", "L&T Infotech", "Zensar"],
      year: 2024,
    },
    reviews: [
      { author: "Chinmay P", rating: 4, comment: "Good college for Pune. Symbiosis brand helps a lot in placements. Campus is modern.", batch: "2022", date: new Date("2024-02-14") },
      { author: "Pallavi M", rating: 3, comment: "Okay college. Placement depends a lot on individual effort and skills.", batch: "2023", date: new Date("2024-09-10") },
    ],
    cutoffs: [
      { exam: "JEE Main", category: "General", rankMin: 60000, rankMax: 200000, course: "B.Tech Computer Science" },
      { exam: "State CET", category: "General", rankMin: 3000, rankMax: 12000, course: "B.Tech Computer Science" },
    ],
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ Connected to MongoDB for seeding");

    // Clear existing data
    await College.deleteMany({});
    console.log("🗑️  Cleared existing college data");

    // Insert seed data
    const inserted = await College.insertMany(colleges);
    console.log(`🌱 Successfully seeded ${inserted.length} colleges`);

    console.log("\n📋 Seeded colleges:");
    inserted.forEach((c, i) => console.log(`  ${i + 1}. ${c.name} (${c.slug})`));

    mongoose.disconnect();
    console.log("\n✅ Seeding complete. MongoDB disconnected.");
  } catch (err) {
    console.error("❌ Seeding error:", err);
    mongoose.disconnect();
    process.exit(1);
  }
}

seed();